<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>eu.oberon-oss</groupId>
        <artifactId>boms</artifactId>
        <version>3.25.4</version>
    </parent>

    <groupId>eu.oberon-oss.tools</groupId>
    <artifactId>converters</artifactId>
    <version>1.1.0</version>


    <name>Converter services library</name>
    <description>
        Utility library providing basic converters for standard Java data items. It allows user-defined functions to perform conversion between classes – both ways.
    </description>
    <scm>
        <connection>scm:git:https://github.com/oberon-oss/converters.git.</connection>
        <developerConnection>scm:git@github.com:oberon-oss/converters.git</developerConnection>
        <url>https://github.com/oberon-oss/converters</url>
    </scm>

    <dependencies>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.5.38</version>
        </dependency>
    </dependencies>

</project>
